apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-service
  labels:
    app: keycloak-service
spec:
  selector:
    matchLabels:
      app: keycloak-service
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-service
    spec:
      containers:
        - name: keycloak-service
          image: gcr.io/ops-terraform-env-cicd/enterprise/keycloak:0.0.25
          args:
            - -b 0.0.0.0
            - -Dkeycloak.migration.action=import
            - -Dkeycloak.migration.provider=singleFile
            - -Dkeycloak.migration.file=/config-files/oauth2-demo-realm-config.json
            - -Dkeycloak.migration.strategy=IGNORE_EXISTING
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: h2
            - name: default_client_secret
              value: 2831f22c-6def-49da-ac3c-ffd256decff0
            - name: pod_namespace
              value: esanchez
          ports:
            - name: kc-container
              containerPort: 8080
          resources:
            requests:
              cpu: 900m
              memory: 1024M
            limits:
              cpu: 3000m
              memory: 1024M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-service
  name: keycloak-service
spec:
  ports:
    - name: web
      port: 7999
      protocol: TCP
      targetPort: kc-container
  selector:
    app: keycloak-service
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-service-ingress
  annotations:
    kubernetes.io/ingress.class: "iap"
spec:
  rules:
    - host: esanchez-keycloak.iap.dev.rktlyr.com
      http:
        paths:
          - path: /
            backend:
              serviceName: keycloak-service
              servicePort: 7999