apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: gcr.io/ops-terraform-env-cicd/enterprise/keycloak:0.0.2
          imagePullPolicy: Always
          args:
            - -b 0.0.0.0
            - -Dkeycloak.migration.action=import
            - -Dkeycloak.migration.provider=singleFile
            - -Dkeycloak.migration.file=/config-files/oauth2-demo-realm-config.json
            - -Dkeycloak.migration.strategy=IGNORE_EXISTING
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: h2
            - name: ent_sso_base_url
              value: https://api-dev.rocketlawyer.com/edu02/v1
          ports:
            - name: kc-container
              containerPort: 8080
          resources:
            requests:
              cpu: 900m
              memory: 1024M
            limits:
              cpu: 3000m
              memory: 1024M
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 7999
      targetPort: kc-container